# Generated by Django 5.2.7 on 2025-10-14 07:16

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="カード会社名"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "store_code",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="店舗コード"
                    ),
                ),
                ("store_name", models.CharField(max_length=100, verbose_name="店舗名称")),
                (
                    "transaction_datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="操作日時"
                    ),
                ),
                (
                    "slip_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="伝票区分"
                    ),
                ),
                (
                    "slip_number",
                    models.CharField(max_length=50, unique=True, verbose_name="伝票番号"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="合計金額(J列)",
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="割引金額"
                    ),
                ),
                (
                    "cash_payment",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="現金支払"
                    ),
                ),
                (
                    "voucher_payment",
                    models.DecimalField(
                        decimal_places=0, default=0, max_digits=10, verbose_name="金券支払"
                    ),
                ),
                ("voucher_count", models.IntegerField(default=0, verbose_name="金券枚数")),
                (
                    "points_used",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="利用ポイント",
                    ),
                ),
                (
                    "payment_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=10,
                        verbose_name="支払(P列)",
                    ),
                ),
                (
                    "card_payment_type",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="カード会社支払い区分(S列)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成日"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新日")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="records.card",
                        verbose_name="カード会社",
                    ),
                ),
            ],
            options={
                "ordering": ["-transaction_datetime"],
            },
        ),
    ]
