# Generated by Django 5.2.7 on 2025-10-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="payment_type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="支払い区分"
            ),
        ),
    ]
