# Generated by Django 5.2.7 on 2025-10-17 00:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_record_payment_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="installments",
            field=models.IntegerField(blank=True, null=True, verbose_name="分割回数"),
        ),
    ]
