# Generated by Django 5.2.7 on 2025-10-17 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_record_installments"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "pos_total",
                    models.DecimalField(
                        decimal_places=0, max_digits=10, verbose_name="レジ合計金額"
                    ),
                ),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="records.card",
                        verbose_name="カード会社",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "card")},
            },
        ),
    ]
