# Generated by Django 5.2.7 on 2025-10-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0004_dailycheck"),
    ]

    operations = [
        migrations.CreateModel(
            name="VoucherCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日付")),
                (
                    "check_time",
                    models.CharField(
                        choices=[
                            ("13:10", "13:10"),
                            ("17:10", "17:10"),
                            ("21:30", "21:30"),
                        ],
                        max_length=5,
                        verbose_name="点検時間",
                    ),
                ),
                ("count", models.IntegerField(verbose_name="枚数")),
            ],
            options={
                "unique_together": {("date", "check_time")},
            },
        ),
    ]
