# Generated by Django 5.2.7 on 2025-10-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0005_vouchercount"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="receipt_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=10,
                null=True,
                verbose_name="レシート金額",
            ),
        ),
    ]
