# Generated by Django 5.2.7 on 2025-10-20 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0007_importbatch_record_batch"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dailycheck",
            name="pos_total",
        ),
        migrations.AddField(
            model_name="dailycheck",
            name="pos_total_1",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="13:10 POS合計"
            ),
        ),
        migrations.AddField(
            model_name="dailycheck",
            name="pos_total_2",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="17:10 POS合計"
            ),
        ),
        migrations.AddField(
            model_name="dailycheck",
            name="pos_total_3",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="21:30 POS合計"
            ),
        ),
    ]
